--POLECENIA

--WHERE


--WYPISAC WSZYSTKICH PILKARZY, KTORY MAJA NUMER POMIEDZY '10' A '20'
SELECT * FROM PILKARZ P
WHERE NUMER BETWEEN 10 AND 20;


--WYSWITLIC WSZYSTKIE PANSTWA, KTORYCH NAZWA KONCZY SIE NA -lia
SELECT G.nazwagrupy, D.nazwapanstwa
FROM druzyna D 
JOIN grupa G ON G.nazwagrupy = D.GRUPA_NAZWAGRUPY
WHERE D.nazwapanstwa LIKE '%lia';

--WYSWIETLIC WSZYSTKICH OBRONCOW HISZPANII W MECZY HISZPANIA - PORTUGALIA
SELECT P.imie, P.nazwisko
FROM pilkarz P 
JOIN rolapikarza R ON P.IDPILKARZ = R.PILKARZ_IDPILKARZ
WHERE P.DRUZYNA_IDDRUZYNY = 1 AND R.MECZ_IDMECZA = 1 AND R.ROLEPILKARZA = 'Obronca';

--WYSWIETLIC WSZYSTKICH PILKARZY KTORYCH NAZWISKO ZACZYNA SIE NA 'M'. WYNIK POSORTOWAC ROSNACO PO IMIENIU
SELECT * FROM PILKARZ P
WHERE P.NAZWISKO LIKE 'M%'
ORDER BY P.IMIE;

--WYSWIETLIC NAZWE DRUZYNY TRENEREM KTOREJ JEST  Didier Deschamps
SELECT D.nazwapanstwa
FROM druzyna D
JOIN trener T ON T.IDTRENERRA = D.TRENER_IDTRENERRA
WHERE T.IMIETRENERA = 'Didier' AND T.NAZWISKOTRENERA = 'Deschamps';


--ZLACZENIE TABEL


--WYSWIETLIC REZYLTAT MECZU W POSTACI: NAZWAPANSWA1  WYNIK  NAZWAPANSTWA2  NAZWASTADIONU
SELECT D1.nazwapanstwa, M.wynik_D1 || '-' || M.wynik_D2 AS "WYNIK",  D2.nazwapanstwa, S.nazwastadionu
FROM MECZ M
JOIN DRUZYNA D1 ON M.IDDRUZYNY1 = D1.IDDRUZYNY
JOIN DRUZYNA D2 ON M.IDDRUZYNY2 = D2.IDDRUZYNY
JOIN STADION S ON M.STADION_IDSTADIONU = S.IDSTADIONU;


--WYSWIETLIC DANE W POSTACI DRUZYNA - TRENER
SELECT D.nazwapanstwa, T.imietrenera || ' ' || T.nazwiskotrenera AS "TRENER"
FROM DRUZYNA D
JOIN TRENER T ON D.TRENER_IDTRENERRA = T.IDTRENERRA;

--WYSWIETLIC DANE W POSTACI IMIE NAZWISKO NUMER PILKARZA - DRUZYNA
SELECT P.IMIE || ' ' || P.NAZWISKO || ' ' || P.NUMER AS "PILKARZ", D.nazwapanstwa
FROM PILKARZ P
JOIN DRUZYNA D ON D.IDDRUZYNY = P.DRUZYNA_IDDRUZYNY;

--WYPISAC NAZWY DRUZYN Z GRUPY 'A' I 'E'
SELECT D.nazwapanstwa
FROM DRUZYNA D
WHERE D.GRUPA_NAZWAGRUPY = 'A'
UNION
SELECT D.nazwapanstwa
FROM DRUZYNA D
WHERE D.GRUPA_NAZWAGRUPY = 'E';

--WYPISAC IMIONA I NAZWISKA PILKARZY, KTORYCH DRUZYNA NIE JEST W GRUPIE 'D' LUB 'E'
SELECT  D.nazwapanstwa, P.IMIE, P.NAZWISKO
FROM PILKARZ P
JOIN DRUZYNA D ON D.IDDRUZYNY = P.DRUZYNA_IDDRUZYNY
MINUS
SELECT D.nazwapanstwa, P.IMIE, P.NAZWISKO
FROM PILKARZ P
JOIN DRUZYNA D ON D.IDDRUZYNY = P.DRUZYNA_IDDRUZYNY
WHERE D.GRUPA_NAZWAGRUPY = 'D' OR D.GRUPA_NAZWAGRUPY = 'E';


--GROUP BY


--POLICZYC ILOSZ STADIONOW W KAZDYM MIASCIE
SELECT M.nazwamiasta, COUNT(*) AS "ILOSC STADIONOW"
FROM stadion S
JOIN miasto M ON M.idmiasta = S.MIASTO_IDMIASTA
GROUP BY M.nazwamiasta;

--WYSWIETLIC ILOSC GRACZY DRUZYNY HISZPANSKIEJ KAZDEJ ROLI PILKARSKIEJ W MECZY HISZPANIA - PORTUGALIA
SELECT D.nazwapanstwa, R.rolepilkarza, COUNT(*) AS "LICZBA GRACZY"
FROM rolapikarza R
JOIN mecz M ON M.idmecza = R.MECZ_IDMECZA
JOIN druzyna D ON D.IDDRUZYNY = M.IDDRUZYNY1
GROUP BY D.nazwapanstwa, R.rolepilkarza;

--WYSWIETLICZ ILOSC GRACZY O IMIENIU ROZPOCZYNAJACYM NA 'A' DRUZYN Z GRUPY 'B'
SELECT D.nazwapanstwa, D.GRUPA_NAZWAGRUPY, COUNT(*) AS "LICZBA PILKARZY"
FROM DRUZYNA D 
JOIN PILKARZ P ON D.IDDRUZYNY = P.DRUZYNA_IDDRUZYNY
WHERE P.IMIE LIKE 'A%'
GROUP BY D.nazwapanstwa, D.GRUPA_NAZWAGRUPY
HAVING D.GRUPA_NAZWAGRUPY = 'B'
ORDER BY D.NAZWAPANSTWA;

SELECT * FROM PILKARZ;

--WYSWIETLICZ STADIONY NA KTORYCH BYL PRZEPROWADZONY PRZYNAJMNIEJ JEDEN MECZ
SELECT S.NAZWASTADIONU, COUNT(*) AS "ILOSC MECZY"
FROM STADION S
JOIN MECZ M ON M.STADION_IDSTADIONU = S.IDSTADIONU
GROUP BY S.NAZWASTADIONU
HAVING COUNT(*)>0;

--WYPISZ ILOSC ZEGRANYCH MECZY DLA KAZDEJ DRUZYNY
SELECT D.NAZWAPANSTWA, COUNT(*) AS "ILOSC MECZY"
FROM DRUZYNA D
JOIN MECZ M ON M.IDDRUZYNY1 = D.IDDRUZYNY OR M.IDDRUZYNY2 = D.IDDRUZYNY
GROUP BY D.NAZWAPANSTWA;

--End of file
